# LuckyBlocks Legacy configuration
#
# Natural generation chance is evaluated when a chunk is populated.
# Set chance to 0 to disable natural Lucky Block generation.

chance: 2
debug: false

world-blacklist:
  - world_nether
  - world_the_end

# Add your own surprises here.
# A surprise may contain normal Minecraft items, Slimefun items and/or commands.
custom:
  ExampleSurprise1:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        type: DIAMOND_SWORD
        amount: 1
        displayname: '&c&lExample Sword'
        lore:
          - '&7This is the lore.'
        enchants:
          - SHARPNESS:5

  ExampleSurprise2:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        slimefun_item: 'BIRTHDAY_CAKE'
        amount: 1

  ExampleSurprise3:
    enabled: false
    lucklevel: UNLUCKY
    commands:
      - 'tell {player} You''re a dead person now!'
      - 'execute as {player} run summon zombie {x} {y} {z}'
